POST http://127.0.0.1:8000/user/createUser
Accept: application/json
Content-Type: application/json

{
  "name": "monNom42",
  "password":"tp",
  "email":"tp@tp.tp"
}
> {%
    client.assert(response.status === 200, 'response status is not 200');
    client.global.set("uuid", response.body.uuid);
    client.log("uuid : " + response.body.uuid);
%}
###
GET http://localhost:8000/auth/getAuthType/{{uuid}}

###
GET http://localhost:8000/user/getUser/{{uuid}}

###

GET http://localhost:8000/user/credit/{{uuid}}/100.25
Accept: application/json
###

GET http://localhost:8000/user/debit/{{uuid}}/100.20
Accept: application/json
###

GET http://localhost:8000/user/debit/{{uuid}}/100.25
Accept: application/json