### Test the first endpoint ###
GET http://127.0.0.1:8081/card/
Accept: application/json

> {%
    client.test("Request is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Test to register ###
POST http://localhost:8083/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "email": "{{email}}"
}

> {%
    client.assert(response.status === 200, 'response status is not 200');
    client.log('response body is ' + response.body);
    client.global.set("user_uuid", response.body.uuid);
    client.global.set("cookie", response.body);
%}

### Add a New Card ###
POST http://localhost:8081/card/addCard
Content-Type: application/json
Cookie: user={{user_uuid}}

{
  "name": "first-card",
  "description": "a test card",
  "imageUrl": "",
  "family": "fire",
  "affinity": "water",
  "hp": 100,
  "attack": 45,
  "defense": 30,
  "energy": 25
}


> {%
    client.test("Request is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("card_uuid", response.body.uuid);
    client.global.set("user_uuid", response.body.ownerUUID);
%}

### Get All Cards ###
GET http://localhost:8081/card/getCards
Accept: application/json;

> {%
    client.test("Request is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Card by UUID ###
GET http://localhost:8081/card/{{card_uuid}}
Accept: application/json

> {%
    client.test("Request is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete Card by UUID ###
< {%
let card_uuid = client.global.get("card_uuid");
client.log(card_uuid);
let user_uuid = client.global.get("user_uuid");
client.log(user_uuid);
%}

DELETE http://localhost:8081/card/{{card_uuid}}
Accept: application/json
Cookie: user={{user_uuid}}

> {%
    client.test("Request is 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    // different to NOT_FOUND
    client.test("Card is deleted", function() {
        client.assert(response.body !== "NOT_FOUND", "Card is not deleted");
    });
%}

### Verify Card is Deleted ###
GET http://localhost:8081/card/{{card_uuid}}
Accept: application/json
Cookie: user={{user_uuid}}

> {%
    client.test("Request is 404", function() {
        client.assert(response.status === 404, "Response status is not 404, the card should have been deleted by the previous test/request");
    });
%}
