POST http://127.0.0.1:{{proxy_port}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "name": "user1",
  "password":"tp",
  "email":"tp@tp.tp"
}
> {%
    client.assert(response.status === 200, 'response status is not 200');
    client.global.set("uuid_from", response.body.uuid);
    client.log("uuid_from : " + response.body.uuid);
%}
###
POST http://127.0.0.1:{{proxy_port}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "name": "user2",
  "password":"tp",
  "email":"tp2@tp.tp"
}
> {%
    client.assert(response.status === 200, 'response status is not 200');
    client.global.set("uuid_to", response.body.uuid);
    client.log("uuid_to : " + response.body.uuid);
%}

### get card by user ###
GET http://127.0.0.1:8000/card/getCardsByOwner/{{uuid_from}}
Accept: application/json
Content-Type: application/json
Cookie: user=tp

> {%
    client.global.set("uuid_card_from", response.body[0].uuid);
    client.log("uuid_card_from : " + response.body[0].uuid);
%}
### get card by user ###
GET http://127.0.0.1:8000/card/getCardsByOwner/{{uuid_to}}
Accept: application/json
Content-Type: application/json
Cookie: user=tp

> {%
    client.global.set("uuid_card_to", response.body[0].uuid);
    client.log("uuid_card_to : " + response.body[0].uuid);
%}
###
POST http://127.0.0.1:{{proxy_port}}/fight/createFight
Accept: application/json
Content-Type: application/json
Cookie: user=tp

{
  "fromCardUUID": "{{uuid_card_from}}",
  "fromUserUUID":"{{uuid_from}}",
  "price": 100
}
> {%
    client.global.set("uuid_fight", response.body.fightUUID);
    client.log("uuid_fight : " + response.body.fightUUID);
%}
###
POST http://127.0.0.1:{{proxy_port}}/fight/acceptFight
Accept: application/json
Content-Type: application/json
Cookie: user=tp

{
  "fightUUID":"{{uuid_fight}}",
  "fromCardUUIS": "{{uuid_card_from}}",
  "fromUserUUID":"{{uuid_from}}",
  "toUserUUID":"{{uuid_to}}",
  "toCardUUID": "{{uuid_card_to}}",
  "price": 100
}

### get user from###
GET http://127.0.0.1:8000/user/getUser/{{uuid_from}}
Accept: application/json
Content-Type: application/json
Cookie: user=tp


### get user to###
GET http://127.0.0.1:8000/user/getUser/{{uuid_to}}
Accept: application/json
Content-Type: application/json
Cookie: user=tp


### get card by user ###
GET http://127.0.0.1:8000/card/getCardsByOwner/{{uuid_from}}
Accept: application/json
Content-Type: application/json
Cookie: user=tp

### get card by user ###
GET http://127.0.0.1:8000/card/getCardsByOwner/{{uuid_to}}
Accept: application/json
Content-Type: application/json
Cookie: user=tp


